// resources/js/vue/components/TagManager.vue
<!--
  ArtisanPack UI Media Library - TagManager Component

  Tag management with create, rename, delete, and attach/detach support.

  @package ArtisanPackUI\MediaLibrary
  @since   1.2.0
-->

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { Button, Input, Textarea, Card, Alert, Badge, Modal } from '@artisanpack-ui/vue';

import type { MediaTag } from '../types/media';

import { fetchTags, createTag, updateTag, deleteTag } from '../utils/api';

const props = withDefaults( defineProps<{
    selectedTag?: string | null;
}>(), {
    selectedTag: null,
} );

const emit = defineEmits<{
    tagsChange: [tags: MediaTag[]];
    tagSelect: [tagSlug: string | null];
}>();

const tags       = ref<MediaTag[]>( [] );
const loading    = ref( true );
const error      = ref<string | null>( null );
const showForm   = ref( false );
const editing    = ref<MediaTag | null>( null );
const deleting          = ref<MediaTag | null>( null );
const showDeleteConfirm = ref( false );
const saving            = ref( false );

const form = reactive( {
    name:        '',
    slug:        '',
    description: '',
} );

function slugify( name: string ): string {
    return name.toLowerCase().replace( /[^a-z0-9]+/g, '-' ).replace( /^-+|-+$/g, '' );
}

async function loadTags() {
    loading.value = true;
    try {
        const response = await fetchTags();
        tags.value     = response.data;
        emit( 'tagsChange', response.data );
    } catch ( err ) {
        error.value = err instanceof Error ? err.message : 'Failed to load tags';
    } finally {
        loading.value = false;
    }
}

onMounted( () => loadTags() );

function resetForm() {
    form.name        = '';
    form.slug        = '';
    form.description = '';
    editing.value    = null;
    showForm.value   = false;
}

function handleEdit( tag: MediaTag ) {
    form.name        = tag.name;
    form.slug        = tag.slug;
    form.description = tag.description || '';
    editing.value    = tag;
    showForm.value   = true;
}

async function handleSave() {
    saving.value = true;
    error.value  = null;

    try {
        const data = {
            name:        form.name,
            slug:        form.slug || slugify( form.name ),
            description: form.description || undefined,
        };

        if ( editing.value ) {
            await updateTag( editing.value.id, data );
        } else {
            await createTag( data );
        }

        resetForm();
        await loadTags();
    } catch ( err ) {
        error.value = err instanceof Error ? err.message : 'Failed to save tag';
    } finally {
        saving.value = false;
    }
}

async function handleDelete() {
    if ( ! deleting.value ) {
        return;
    }

    saving.value = true;
    error.value  = null;

    try {
        const deletedSlug = deleting.value.slug;
        await deleteTag( deleting.value.id );
        deleting.value          = null;
        showDeleteConfirm.value = false;
        if ( props.selectedTag === deletedSlug ) {
            emit( 'tagSelect', null );
        }
        await loadTags();
    } catch ( err ) {
        error.value = err instanceof Error ? err.message : 'Failed to delete tag';
    } finally {
        saving.value = false;
    }
}
</script>

<template>
    <Card>
        <div class="flex items-center justify-between mb-3">
            <h3 class="text-sm font-bold">Tags</h3>
            <Button size="sm" color="primary" @click="resetForm(); showForm = true">
                <svg class="w-4 h-4 mr-1" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
                New
            </Button>
        </div>

        <Alert v-if="error" color="error" class="mb-3">{{ error }}</Alert>

        <!-- Tag list -->
        <div class="flex flex-wrap gap-2">
            <button type="button" class="cursor-pointer rounded-full hover:opacity-80 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" :aria-pressed="selectedTag === null" @click="emit( 'tagSelect', null )">
                <Badge value="All" :color="selectedTag === null ? 'primary' : 'neutral'" />
            </button>

            <div v-for="tag in tags" :key="tag.id" class="group relative inline-flex" tabindex="0">
                <button type="button" class="cursor-pointer rounded-full hover:opacity-80 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" :aria-pressed="selectedTag === tag.slug" @click="emit( 'tagSelect', tag.slug )">
                    <Badge
                        :value="`${ tag.name }${ tag.media_count !== undefined ? ` (${ tag.media_count })` : '' }`"
                        :color="selectedTag === tag.slug ? 'primary' : 'neutral'"
                    />
                </button>

                <div class="absolute -top-1 -right-1 invisible flex gap-0.5 group-hover:visible group-focus-within:visible">
                    <button type="button" class="w-4 h-4 rounded-full bg-base-300 flex items-center justify-center cursor-pointer hover:bg-base-content/20 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1 disabled:cursor-not-allowed disabled:opacity-50" :aria-label="`Edit ${ tag.name }`" @click="handleEdit( tag )">
                        <svg class="w-2.5 h-2.5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931z" />
                        </svg>
                    </button>
                    <button type="button" class="w-4 h-4 rounded-full bg-error text-error-content flex items-center justify-center cursor-pointer hover:bg-error/80 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1 disabled:cursor-not-allowed disabled:opacity-50" :aria-label="`Delete ${ tag.name }`" @click="deleting = tag; showDeleteConfirm = true">
                        <svg class="w-2.5 h-2.5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <!-- Create/Edit form -->
        <Teleport to="body">
            <Modal v-if="showForm" v-model:open="showForm" :title="editing ? 'Edit Tag' : 'New Tag'" @update:open="( v ) => { if ( ! v ) resetForm(); }">
                <div class="flex flex-col gap-4">
                    <Input label="Name" v-model="form.name" placeholder="Tag name" @update:model-value="( v ) => { if ( ! editing ) form.slug = slugify( v as string ); }" />
                    <Input label="Slug" v-model="form.slug" placeholder="tag-slug" hint="URL-friendly identifier" />
                    <Textarea label="Description" v-model="form.description" placeholder="Optional description" />
                </div>
                <template #actions>
                    <Button @click="resetForm()">Cancel</Button>
                    <Button color="primary" :loading="saving" @click="handleSave()">{{ editing ? 'Update' : 'Create' }}</Button>
                </template>
            </Modal>
        </Teleport>

        <!-- Delete confirmation -->
        <Teleport to="body">
            <Modal v-if="showDeleteConfirm" v-model:open="showDeleteConfirm" title="Delete Tag" @update:open="( v ) => { if ( ! v ) { deleting = null; showDeleteConfirm = false; } }">
                <p>Are you sure you want to delete the tag <strong>{{ deleting?.name }}</strong>? It will be detached from all media items.</p>
                <template #actions>
                    <Button @click="deleting = null; showDeleteConfirm = false">Cancel</Button>
                    <Button color="error" :loading="saving" @click="handleDelete()">Delete</Button>
                </template>
            </Modal>
        </Teleport>
    </Card>
</template>

// resources/js/react/components/TagManager.tsx
/**
 * ArtisanPack UI Media Library - TagManager Component
 *
 * Tag management with create, rename, delete, and attach/detach support.
 *
 * @package ArtisanPackUI\MediaLibrary
 * @since   1.2.0
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Button, Input, Textarea, Card, Alert, Badge, Modal } from '@artisanpack-ui/react';
import { cn } from '@artisanpack-ui/tokens';

import type { MediaTag } from '../types/media';

import { fetchTags, createTag, updateTag, deleteTag } from '../utils/api';
import { Portal } from '../utils/Portal';

/**
 * Props for the TagManager component.
 */
export interface TagManagerProps {
    /** Called when tags change. */
    onTagsChange?: ( tags: MediaTag[] ) => void;
    /** Called when a tag is selected for filtering. */
    onTagSelect?: ( tagSlug: string | null ) => void;
    /** Currently selected tag slug. */
    selectedTag?: string | null;
    /** Additional CSS class names. */
    className?: string;
}

/**
 * Generate a slug from a name.
 */
function slugify( name: string ): string {
    return name
        .toLowerCase()
        .replace( /[^a-z0-9]+/g, '-' )
        .replace( /^-+|-+$/g, '' );
}

/**
 * Tag management component.
 */
export const TagManager: React.FC<TagManagerProps> = ( {
    onTagsChange,
    onTagSelect,
    selectedTag = null,
    className,
} ) => {
    const [ tags, setTags ]           = useState<MediaTag[]>( [] );
    const [ loading, setLoading ]     = useState( true );
    const [ error, setError ]         = useState<string | null>( null );
    const [ showForm, setShowForm ]   = useState( false );
    const [ editing, setEditing ]     = useState<MediaTag | null>( null );
    const [ deleting, setDeleting ]   = useState<MediaTag | null>( null );
    const [ saving, setSaving ]       = useState( false );

    const [ form, setForm ] = useState( {
        name:        '',
        slug:        '',
        description: '',
    } );

    const onTagsChangeRef   = useRef( onTagsChange );
    onTagsChangeRef.current = onTagsChange;

    const loadTags = useCallback( async () => {
        setLoading( true );
        try {
            const response = await fetchTags();
            setTags( response.data );
            onTagsChangeRef.current?.( response.data );
        } catch ( err ) {
            setError( err instanceof Error ? err.message : 'Failed to load tags' );
        } finally {
            setLoading( false );
        }
    }, [] );

    useEffect( () => {
        loadTags();
    }, [ loadTags ] );

    const resetForm = useCallback( () => {
        setForm( { name: '', slug: '', description: '' } );
        setEditing( null );
        setShowForm( false );
    }, [] );

    const handleEdit = useCallback( ( tag: MediaTag ) => {
        setForm( {
            name:        tag.name,
            slug:        tag.slug,
            description: tag.description || '',
        } );
        setEditing( tag );
        setShowForm( true );
    }, [] );

    const handleSave = useCallback( async () => {
        setSaving( true );
        setError( null );

        try {
            const data = {
                name:        form.name,
                slug:        form.slug || slugify( form.name ),
                description: form.description || undefined,
            };

            if ( editing ) {
                await updateTag( editing.id, data );
            } else {
                await createTag( data );
            }

            resetForm();
            await loadTags();
        } catch ( err ) {
            setError( err instanceof Error ? err.message : 'Failed to save tag' );
        } finally {
            setSaving( false );
        }
    }, [ form, editing, resetForm, loadTags ] );

    const handleDelete = useCallback( async () => {
        if ( ! deleting ) {
            return;
        }

        setSaving( true );
        setError( null );

        try {
            const deletedSlug = deleting.slug;
            await deleteTag( deleting.id );
            setDeleting( null );
            if ( selectedTag === deletedSlug ) {
                onTagSelect?.( null );
            }
            await loadTags();
        } catch ( err ) {
            setError( err instanceof Error ? err.message : 'Failed to delete tag' );
        } finally {
            setSaving( false );
        }
    }, [ deleting, selectedTag, onTagSelect, loadTags ] );

    return (
        <Card className={ className }>
            <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-bold">Tags</h3>
                <Button
                    size="sm"
                    color="primary"
                    onClick={ () => {
                        resetForm();
                        setShowForm( true );
                    } }
                >
                    <svg className="w-4 h-4 mr-1" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={ 2 }>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                    </svg>
                    New
                </Button>
            </div>

            { error && <Alert type="error" className="mb-3">{ error }</Alert> }

            { /* Tag list */ }
            <div className="flex flex-wrap gap-2">
                { /* All tags option */ }
                <button
                    type="button"
                    className="cursor-pointer rounded-full hover:opacity-80 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    onClick={ () => onTagSelect?.( null ) }
                >
                    <Badge
                        value="All"
                        color={ selectedTag === null ? 'primary' : 'neutral' }
                    />
                </button>

                { tags.map( ( tag ) => (
                    <div key={ tag.id } className="group relative inline-flex" tabIndex={ 0 }>
                        <button
                            type="button"
                            className="cursor-pointer rounded-full hover:opacity-80 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                            onClick={ () => onTagSelect?.( tag.slug ) }
                        >
                            <Badge
                                value={ `${ tag.name }${ tag.media_count !== undefined ? ` (${ tag.media_count })` : '' }` }
                                color={ selectedTag === tag.slug ? 'primary' : 'neutral' }
                            />
                        </button>

                        <div className="absolute -top-1 -right-1 invisible flex gap-0.5 group-hover:visible group-focus-within:visible">
                            <button
                                type="button"
                                className="w-4 h-4 rounded-full bg-base-300 flex items-center justify-center cursor-pointer hover:bg-base-content/20 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1 disabled:cursor-not-allowed disabled:opacity-50"
                                onClick={ () => handleEdit( tag ) }
                                aria-label={ `Edit ${ tag.name }` }
                            >
                                <svg className="w-2.5 h-2.5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={ 2 }>
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931z" />
                                </svg>
                            </button>
                            <button
                                type="button"
                                className="w-4 h-4 rounded-full bg-error text-error-content flex items-center justify-center cursor-pointer hover:bg-error/80 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1 disabled:cursor-not-allowed disabled:opacity-50"
                                onClick={ () => setDeleting( tag ) }
                                aria-label={ `Delete ${ tag.name }` }
                            >
                                <svg className="w-2.5 h-2.5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={ 2 }>
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                    </div>
                ) ) }
            </div>

            { /* Create/Edit form */ }
            { showForm && (
            <Portal>
            <Modal
                open
                onClose={ resetForm }
                title={ editing ? 'Edit Tag' : 'New Tag' }
                actions={
                    <>
                        <Button onClick={ resetForm }>Cancel</Button>
                        <Button
                            color="primary"
                            onClick={ handleSave }
                            loading={ saving }
                        >
                            { editing ? 'Update' : 'Create' }
                        </Button>
                    </>
                }
            >
                <div className="flex flex-col gap-4">
                    <Input
                        label="Name"
                        value={ form.name }
                        onChange={ ( e ) => {
                            const name = e.target.value;
                            setForm( ( prev ) => ( {
                                ...prev,
                                name,
                                slug: editing ? prev.slug : slugify( name ),
                            } ) );
                        } }
                        placeholder="Tag name"
                    />
                    <Input
                        label="Slug"
                        value={ form.slug }
                        onChange={ ( e ) => setForm( ( prev ) => ( { ...prev, slug: e.target.value } ) ) }
                        placeholder="tag-slug"
                        hint="URL-friendly identifier"
                    />
                    <Textarea
                        label="Description"
                        value={ form.description }
                        onChange={ ( e ) => setForm( ( prev ) => ( { ...prev, description: e.target.value } ) ) }
                        placeholder="Optional description"
                    />
                </div>
            </Modal>
            </Portal>
            ) }

            { /* Delete confirmation */ }
            { deleting && (
            <Portal>
            <Modal
                open
                onClose={ () => setDeleting( null ) }
                title="Delete Tag"
                actions={
                    <>
                        <Button onClick={ () => setDeleting( null ) }>Cancel</Button>
                        <Button
                            color="error"
                            onClick={ handleDelete }
                            loading={ saving }
                        >
                            Delete
                        </Button>
                    </>
                }
            >
                <p>
                    Are you sure you want to delete the tag <strong>{ deleting.name }</strong>?
                    It will be detached from all media items.
                </p>
            </Modal>
            </Portal>
            ) }
        </Card>
    );
};
